#!/bin/sh -e
# pick a random palette from a directory
# usage: 'shuffle'

# palette directory (hint: change this!)
set -- ~/projects/paleta/palettes/*-dark

# cache file for paleta output
paleta_file=~/.pal


rand() {
    # random int via /dev/urandom
    LC_ALL=C tr -dc 1-9 < /dev/urandom |
        dd ibs=1 obs=1 count=5 2>/dev/null
}

cols() {
    # print 16 color palette
    for i in 1 2 3 4 5 6; do
        printf '\033[4%sm  \033[m' "$i"
        printf '\033[10%sm  \033[m' "$i"
    done

    printf '\n\n'
}

main() {
    [ -f "$1" ] || {
        printf 'no palettes found in dir\n'
        exit 1;
    }

    shift "$(($(rand) % $#))"

    # call ourselves again if we found nothing
    [ -f "$1" ] || {
        exec "$0"
    }

    printf "\n%s\n" "${1##*/}"

    # replace '> ~/.pal' with your equivalent
    paleta < "$1" > "$paleta_file"
    cols
}

main "$@"
