.TH PAL 1
.SH NAME
pal \- a unix-style program to change terminal color-schemes on the fly
.SH SYNOPSIS
.B pal
\fB\-r\fR

.B pal
\fB\-v\fR

.B pal
[\fBcolors\fR] (See \fBCOLORS\fR below)

.B pal
.IR file ...
.SH DESCRIPTION
.B pal
takes 16 colors as input. Color 0 is assumed to be the background color and color 15 is assumed to be the foreground color. When less than 16 colors are supplied, pal repeats the last color till 16.

A list of hex colors are supplied via command-line arguments, stdin or a file and pal sends these colors to all open terminals, modifying their palette. The purpose of this tool is to allow theme managers and individual scripts to effortlessly modify the current color-scheme without needing a reload of running terminals.

.SH COLORS

Colors can be input to \fBpal\fR in the following ways; As command-line arguments (pal 000000 111111 222222 ...), As a string (pal "000000 111111 222222" ...), as a file (pal file) or through \fBstdin\fR.


.SH OPTIONS
.TP
.BR \-r
Apply current colors to current terminal.
.TP
.BR \-h
Show usage and exit.
.TP
.BR \-v
Show version and exit.

