#!/bin/sh
#
# paleta - change terminal colors on the fly.

mkdir -p "${cache_dir:=${XDG_CACHE_HOME:=$HOME/.cache}/paleta}"

case $1 in
    -h) printf 'usage: paleta -r, paleta [col]...\n'; exit 1 ;;
    -r) cat "$cache_dir/colors" 2>/dev/null; exit ;;
    -v) printf 'paleta 1.0.0\n'; exit ;;
     *) set -- ;;
esac

while read -r col; do
    [ "$#" -gt 16 ] && {
        printf 'warn: more than 16 colors given, ignoring excess\n' >&2
        break
    }

    set -- "$@" "$col"
done

[ "$#" -lt 16 ] && {
    printf 'warn: less than 16 colors given, duplicating input\n' >&2

    while [ "$#" -lt 16 ]; do
        set -- "$@" "${2:-FFFFFF}"
    done
}

# Construct sequence list of 0-15 colors.
for col do
    seq="$seq]4;${i:=0};#${col#\#}\\"

    : "$((i+=1))"
done

# 10: Foreground color, 11: Background color, 12: Cursor Foreground color.
# Source: https://goo.gl/KcoQgP
seq="$seq]10;${15}\\]11;$1\\]12;${15}\\"

# Border Background color (various terminals).
# Skip this sequence if running in VTE.)
[ "$VTE_VERSION" ] || seq="$seq]708;$1\\"

# Send escape sequences to all open terminals.
for tty in /dev/pts/[0-9]*; do
    [ -w "$tty" ] && printf %b "$seq" > "$tty" &
done
printf %b "$seq" > "$cache_dir/colors"
