.TH PALETA 1
.SH NAME
paleta \- change terminal colors on the fly
.SH SYNOPSIS
.B paleta
\fB\-r\fR

.B paleta
\fB\-v\fR

.B paleta
[\fBcolors\fR] (See \fBCOLORS\fR below)

.B paleta
.IR file ...
.SH DESCRIPTION
.B paleta
takes 16 colors as input. Color 0 is assumed to be the background color and color 15 is assumed to be the foreground color. When less than 16 colors are supplied, paleta repeats the last color till 16.

A list of hex colors are supplied via command-line arguments, stdin or a file and paleta sends these colors to all open terminals, modifying their palette. The purpose of this tool is to allow theme managers and individual scripts to effortlessly modify the current color-scheme without needing a reload of running terminals.

.SH COLORS

Colors can be input to \fBpaleta\fR in the following ways; As command-line arguments (paleta 000000 111111 222222 ...), As a string (paleta "000000 111111 222222" ...), as a file (paleta file) or through \fBstdin\fR.


.SH OPTIONS
.TP
.BR \-r
Apply current colors to current terminal.
.TP
.BR \-h
Show usage and exit.
.TP
.BR \-v
Show version and exit.

